# Generated by Django 2.0.5 on 2018-10-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphanumeric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphanumeric_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Atbash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atbash_test', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Caesar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caesar_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Viginere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viginere_text', models.CharField(max_length=500)),
            ],
        ),
    ]
