# Generated by Django 2.0.5 on 2018-10-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atbash',
            old_name='atbash_test',
            new_name='atbash_text',
        ),
    ]
